# Generated by Django 5.2.12 on 2026-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_total_xp_remove_profile_tree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lớp học (VD: 1A1)'),
        ),
    ]
