# Generated by Django 5.2.12 on 2026-05-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_student_class'),
        ('learning', '0003_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.classroom', verbose_name='Lớp học'),
        ),
    ]
