# Generated by Django 5.2.12 on 2026-05-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=255, verbose_name='Mặt trước (Thuật ngữ)')),
                ('back_text', models.TextField(verbose_name='Mặt sau (Định nghĩa)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.lesson', verbose_name='Bài học')),
            ],
        ),
    ]
