# Generated by Django 5.2.12 on 2026-05-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên Lớp (VD: 10A1)')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='learning.grade', verbose_name='Khối lớp')),
            ],
        ),
    ]
