"""
Django settings for lms_core project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^@8qjz=gl!=p#xuj2ao34cx#ky&$2udx(p0ifvz*&u$$0ddk5*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis', # BẮT BUỘC: Kích hoạt hỗ trợ PostGIS cho hệ thống GIS Maps
    
    # --- Custom Apps của đồ án ---
    'apps.accounts',
    'apps.learning',
    'apps.gis_maps',
    'apps.gamification',
    'apps.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lms_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Đã gom layout về thư mục templates/ ở root
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms_core.wsgi.application'


# Database
# Cấu hình chuyển sang PostgreSQL kết hợp PostGIS cho bài giảng Địa lý/Lịch sử

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Engine bản đồ số
        'NAME': 'lms_db',
        'USER': 'postgres',       # User mặc định của pgAdmin
        'PASSWORD': '123',  # CẦN SỬA: Thay bằng mật khẩu PostgreSQL trên máy của bạn
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# Cấu hình chuẩn cho đồ án tại Việt Nam

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] # Thư mục chứa CSS/JS tự code

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'          # Thư mục lưu file user upload (Báo cáo PDF, ảnh GIS)

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

# --- CẤU HÌNH FIX LỖI GDAL CHO WINDOWS ---
if os.name == 'nt':
    # Đường dẫn trỏ thẳng vào ổ D của bạn
    POSTGIS_BIN_PATH = r"D:\PostgreSQL\16\bin"
    
    # Cấp quyền cho Python đọc các file .dll
    if hasattr(os, 'add_dll_directory'):
        try:
            os.add_dll_directory(POSTGIS_BIN_PATH)
        except FileNotFoundError:
            pass
            
    # Trỏ đích danh tới file GDAL 35 và GEOS
    GDAL_LIBRARY_PATH = os.path.join(POSTGIS_BIN_PATH, 'libgdal-35.dll')
    GEOS_LIBRARY_PATH = os.path.join(POSTGIS_BIN_PATH, 'libgeos_c.dll')


# Thiết lập Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'