# Generated by Django 5.2.12 on 2026-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='current_level_xp',
            field=models.IntegerField(default=0),
        ),
    ]
