# Generated by Django 5.2.12 on 2026-05-10 08:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='Câu hỏi (VD: Click vào tỉnh Nghệ An, Click vào vị trí Dinh Độc Lập)')),
                ('target_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Vùng đáp án đúng')),
                ('target_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Tọa độ đúng')),
                ('tolerance_radius', models.FloatField(default=5000, verbose_name='Sai số cho phép (mét)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_questions', to='learning.lesson', verbose_name='Bài học GIS')),
            ],
        ),
    ]
